# Generated by Django 5.1.15 on 2026-07-14 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('pre_test', 'Pre-Test (Diagnostic)'), ('post_test', 'Post-Test (Final)')], default='standard', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_type__in', ['pre_test', 'post_test'])), fields=('course', 'quiz_type'), name='unique_pre_post_test_per_course'),
        ),
    ]
