# Generated by Django 5.1.15 on 2026-07-14 06:58

from django.db import migrations, models


def backfill_certificate_hash(apps, schema_editor):
    """No certificates exist yet in this project's own database, but
    this keeps the migration safe to run against any environment that
    already has issued certificates — every existing row gets a real
    hash computed from its actual field values, not an empty
    placeholder."""
    from apps.certificates.models import compute_certificate_hash

    Certificate = apps.get_model("certificates", "Certificate")
    for certificate in Certificate.objects.filter(certificate_hash=""):
        certificate.certificate_hash = compute_certificate_hash(
            certificate.certificate_number, certificate.student_id, certificate.course_id
        )
        certificate.save(update_fields=["certificate_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_certificate_hash, migrations.RunPython.noop),
    ]
