# Generated by Django 5.1.15 on 2026-07-14 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('seeking', 'Seeking Employment'), ('internship', 'Internship'), ('freelancing', 'Freelancing'), ('business_owner', 'Business Owner'), ('employed_full_time', 'Employed Full-Time'), ('employed_part_time', 'Employed Part-Time'), ('promoted', 'Promoted'), ('unemployed', 'Unemployed')], max_length=30)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_employed', models.DateField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, choices=[('under_50k', 'Under $50,000/year (or local equivalent)'), ('50k_100k', '$50,000 - $100,000/year'), ('100k_150k', '$100,000 - $150,000/year'), ('over_150k', 'Over $150,000/year'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True)),
                ('how_academy_helped', models.TextField(blank=True)),
                ('evidence_storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='employment__student_56d11f_idx')],
            },
        ),
    ]
