# Generated by Django 5.1.15 on 2026-07-10 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('content_quality', models.PositiveSmallIntegerField()),
                ('instructor_effectiveness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('practical_lab_quality', models.PositiveSmallIntegerField()),
                ('platform_experience', models.PositiveSmallIntegerField()),
                ('most_helpful', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course'], name='feedback_st_course__239b30_idx'), models.Index(fields=['instructor'], name='feedback_st_instruc_5c9ecc_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='one_feedback_per_student_per_course'), models.CheckConstraint(condition=models.Q(('overall_rating__gte', 1), ('overall_rating__lte', 5)), name='overall_rating_1_to_5'), models.CheckConstraint(condition=models.Q(('content_quality__gte', 1), ('content_quality__lte', 5)), name='content_quality_1_to_5'), models.CheckConstraint(condition=models.Q(('practical_lab_quality__gte', 1), ('practical_lab_quality__lte', 5)), name='lab_quality_1_to_5'), models.CheckConstraint(condition=models.Q(('platform_experience__gte', 1), ('platform_experience__lte', 5)), name='platform_experience_1_to_5'), models.CheckConstraint(condition=models.Q(('instructor_effectiveness__isnull', True), models.Q(('instructor_effectiveness__gte', 1), ('instructor_effectiveness__lte', 5)), _connector='OR'), name='instructor_effectiveness_1_to_5_or_null')],
            },
        ),
    ]
