# Generated by Django 5.1.15 on 2026-07-14 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('linux', 'Linux'), ('networking', 'Networking'), ('nmap', 'Nmap'), ('wireshark', 'Wireshark'), ('burp_suite', 'Burp Suite'), ('owasp', 'OWASP'), ('web_security', 'Web Security'), ('soc', 'SOC Labs'), ('threat_hunting', 'Threat Hunting'), ('digital_forensics', 'Digital Forensics'), ('cloud_security', 'Cloud Security'), ('python_security_automation', 'Python Security Automation'), ('ai_security_engineering', 'AI Security Engineering')], max_length=40)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('allow_resubmission', models.BooleanField(default=True, help_text='If enabled, a student may restart this lab before it is graded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_labs', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_labs_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_labs', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('score', models.FloatField(blank=True, null=True)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_progress_graded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_progress', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='labs.practicallab')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='practicallab',
            index=models.Index(fields=['course', 'status'], name='labs_practi_course__283398_idx'),
        ),
        migrations.AddIndex(
            model_name='labprogress',
            index=models.Index(fields=['student', 'status'], name='labs_labpro_student_fb5380_idx'),
        ),
        migrations.AddConstraint(
            model_name='labprogress',
            constraint=models.UniqueConstraint(fields=('lab', 'student'), name='unique_progress_per_student_lab'),
        ),
    ]
