# Generated by Django 5.1.15 on 2026-07-14 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smes_protected', models.PositiveIntegerField(default=0, help_text='SMEs protected from cyber threats')),
                ('healthcare_workers_trained', models.PositiveIntegerField(default=0)),
                ('businesses_started', models.PositiveIntegerField(default=0, help_text='Businesses started by graduates as a direct result of training')),
                ('notes', models.TextField(blank=True, help_text='Source/context for these figures (e.g. survey, partner report)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
